language: cpp
dist: jammy  # Ubuntu 22.04 LTS
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

cache:
  directories:
    - $HOME/.ccache
  ccache: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update && sudo apt-get install -y build-essential libtool autotools-dev autoconf pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libminiupnpc-dev libzmq3-dev libdb4.8-dev libdb4.8++-dev qt5-default; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install boost libevent openssl berkeley-db4 miniupnpc zeromq qt5; fi

script:
  - ./autogen.sh
  - ./configure --with-gui=qt5 --enable-tests --enable-zmq
  - make -j$(nproc)
  - make check

notifications:
  email:
    recipients:
      - your-email@example.com
    on_success: change
    on_failure: always

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "src/lpscoinsd"
  skip_cleanup: true
  on:
    tags: true
