# GitHub Actions workflow for building and testing LPSCoin Core using Autoconf/Automake
name: LPSCoin Core Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev autoconf pkg-config libssl-dev libevent-dev libboost-all-dev libminiupnpc-dev libzmq3-dev libdb4.8-dev libdb4.8++-dev qt5-default

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          configure
          Makefile
          src/Makefile
        key: ${{ runner.os }}-autoconf-${{ hashFiles('configure.ac', 'Makefile.am', 'src/Makefile.am') }}

    - name: Generate build files
      if: steps.cache.outputs.cache-hit != 'true'
      run: ./autogen.sh

    - name: Configure build
      if: steps.cache.outputs.cache-hit != 'true'
      run: ./configure --with-gui=qt5 --enable-zmq

    - name: Build
      run: make -j$(nproc)

    - name: Run tests
      run: make check
